#file: noinspection SpellCheckingInspection,YAMLSchemaValidation
service: drinkbuy-wss-lambda-commands
frameworkVersion: ">=3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  deploymentMethod: direct
  vpc:
    securityGroupIds:
      - sg-0926ec66a0702d5c2
    subnetIds:
      - subnet-0d0781add70b61a44
      - subnet-0a9478b6b5f6c3fd4
  environment:
    DDB_LOCAL_ENDPOINT:
    MONGODB_URI: ${env:MONGODB_URI, ssm:/drinkbuy/wss-lambda/dev/MONGODB_URI}
    MONGODB_USER: ${env:MONGODB_USER, ssm:/drinkbuy/wss-lambda/dev/MONGODB_USER}
    MONGODB_PASS: ${env:MONGODB_PASS, ssm:/drinkbuy/wss-lambda/dev/MONGODB_PASS}
    CONNECTIONS_TABLE: websocket-lambda-connections-${sls:stage}
    JWT_SECRET: ${env:JWT_SECRET, ssm:/drinkbuy/wss-lambda/dev/JWT_SECRET}
    SOCKET_CORS_ORIGIN: ${env:SOCKET_CORS_ORIGIN, ssm:/drinkbuy/wss-lambda/dev/SOCKET_CORS_ORIGIN}
    API_GW_WS_ENDPOINT: ${env:API_GW_WS_ENDPOINT, ssm:/drinkbuy/wss-lambda/dev/API_GW_WS_ENDPOINT}
    WEBSOCKET_API_ENDPOINT: ${env:WEBSOCKET_API_ENDPOINT, "${ssm:/drinkbuy/wss-lambda/dev/WEBSOCKET_API_ENDPOINT}/${sls:stage}"}

    #SOCKET_CORS_ORIGIN: ${env:SOCKET_CORS_ORIGIN, "http://localhost:4000"}
    #API_GW_WS_ENDPOINT: ${env:API_GW_WS_ENDPOINT, "http://localhost:4001"}

    WEBSOCKET_DOMAIN: ${env:WEBSOCKET_DOMAIN, ssm:/drinkbuy/wss-lambda/dev/WEBSOCKET_DOMAIN}
    WEBSOCKET_STAGE: ${opt:stage, 'dev'}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:CreateTable
            - dynamodb:DescribeTable
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
            - dynamodb:Query
          Resource:
            - Fn::GetAtt: [ConnectionsTable, Arn]
        - Effect: Allow
          Action:
            - execute-api:ManageConnections
          Resource:
            - arn:aws:execute-api:*:*:*/@connections/*

functions:
  websocket:
    handler: src/handlers/websocket.handler
    timeout: 30
    memorySize: 512
    events:
      - websocket: { route: $connect }
      - websocket: { route: $disconnect }
      - websocket: { route: $default }
      - websocket: { route: "user-commands-ack" }

  barOpenClose:
    name: drinkbuy-wss-lambda-commands-${sls:stage}-bar-open-close
    handler: src/handlers/bar-open-close.handler
    timeout: 120
    memorySize: 512
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true
          input:
            action: scheduled_open_closed_bars
            job: bar_open_close

  httpPublish:
    name: drinkbuy-wss-lambda-commands-${sls:stage}-http-publish
    handler: src/handlers/http-publish.handler
    events:
      - httpApi:
          method: POST
          path: /publish-command

resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: websocket-lambda-connections-${sls:stage}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

plugins:
  #- serverless-dotenv-plugin
  - serverless-offline
  #- serverless-dynamodb-local
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    sourcemap: true
    target: node20
    platform: node
    external:
      - aws-sdk
  dynamodb:
    stages: [dev]
    start:
      dbPath: ./.ddb
      port: 8000
      inMemory: false
      migrate: true

  serverless-offline:
    httpPort: ${env:HTTP_PORT, 4000}
    websocketPort: ${env:WS_PORT, 4001}
    lambdaPort: ${env:LAMBDA_PORT, 4002}
